//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by STEPViewer.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MySTEPViewerTYPE            130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_INSTANCES_SORTALPHABETIC 146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_INSTANCES_SORTBYTYPE 147
#define ID_SORTING_SORTBYACCESS         148
#define ID_SORTING_INSTANCES_NOT_REFERENCED 148
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_POPUP_INSTANCES             310
#define ID_COMBO_PROPERTIES_VIEW        310
#define IDR_POPUP_SORT_INSTANCES        311
#define IDR_SORT_INSTANCES              311
#define IDC_TREE_INSTANCE_VIEW          311
#define IDB_SORT_INSTANCES_24           312
#define TEXTFILE                        312
#define IDD_DIALOG_EDIT_OBJECT_PROPRTY  313
#define IDD_DIALOG_NEW_INSTANCE         314
#define IDR_POPUP_INSTANCES_NO_GEOMETRY 315
#define IDD_DIALOG_SEARCH               316
#define IDD_DIALOG_SELECT_INSTANCE      318
#define IDD_MODELCHECK                  319
#define IDR_MENU_3D_VIEW                320
#define IDB_NONE                        322
#define IDB_PROPERTY                    323
#define IDB_PROPERTY_SET                324
#define IDB_SELECTED_ALL                325
#define IDB_SELECTED_NONE               326
#define IDB_SELECTED_PART               327
#define IDR_TEXTFILE_VERTEX_SHADER2     331
#define IDR_TEXTFILE_FRAGMENT_SHADER2   332
#define IDS_IFC_RELATIONS_VIEW          334
#define IDS_VIEW_IFC_RELATIONS          335
#define IDS_VIEW_ORIGIN                 336
#define IDS_IGNORE_ATTRIBUTE            337
#define IDS_SAVE_SCHEMA                 338
#define IDS_LOAD_SCHEMA                 339
#define IDS_VIEW_GEOMETRY               340
#define IDS_VIEW_INSTANCE_PROPERTIES    341
#define IDC_TREE_IFC                    342
#define IDS_SCHEMA_VIEW                 343
#define ID_VIEW_SCHEMA                  344
#define ID_VIEW_RELATIONS               345
#define ID_VIEW_DESIGN                  346
#define IDS_DESIGN_VIEW                 347
#define IDR_POPUP_META_DATA             348
#define IDR_TEXTFILE_VERTEX_SHADER3     349
#define IDR_TEXTFILE_FRAGMENT_SHADER3   350
#define IDC_COMBO_EXISTING_INSTANCE     1000
#define IDC_RADIO_EXISTING_INSTANCE     1001
#define IDC_RADIO_NEW_INSTANCE          1002
#define IDC_ISSUELIST                   1002
#define IDC_COMBO_NEW_INSTANCE          1003
#define ID_APPLY_CHANGES                1004
#define IDC_COMBO_CLASSES               1005
#define IDC_VIEW_ALL_ISSUES             1005
#define IDC_BUTTON_SEARCH               1006
#define IDC_EDIT_SEARCH_TEXT            1007
#define IDC_COMBO_SEARCH_FILTER         1008
#define IDC_COMBO_INSTANCES             1009
#define ID_INSTANCES_ZOOM_TO            32772
#define ID_INSTANCES                    32773
#define ID_INSTANCES_METAINFORMATION    32778
#define ID_INSTANCES_META_INFORMATION   32779
#define ID_INSTANCES_DISABLE_ALL_BUT_THIS 32781
#define ID_INSTANCES_ENABLEALL          32782
#define ID_INSTANCES_ENABLE_ALL         32783
#define ID_INSTANCES_ENABLE             32784
#define ID_NEW_INSTANCE                 32785
#define ID_INSTANCES_REMOVE             32786
#define ID_INSTANCES_ADDMEASUREMENTS    32787
#define ID_INSTANCES_ADD_MEASUREMENTS   32788
#define ID_VIEW_CHECKFORUNIQUEVERTICES  32789
#define ID_INSTANCES_REMOVE_TREE        32790
#define ID_INSTANCES_SAVE               32791
#define ID_INSTANCES_SEARCH             32792
#define ID_Menu                         32796
#define ID_VIEW_CENTER_ALL_GEOMETRY     32805
#define ID_VIEW_ZOOM_OUT                32807
#define ID_VIEW_PROJECTION              32808
#define ID_PROJECTION_PERSPECTIVE       32809
#define ID_PROJECTION_ORTHOGRAPHIC      32810
#define ID_VIEW_VIEW                    32811
#define ID_VIEW_FRONT                   32812
#define ID_VIEW_TOP                     32813
#define ID_VIEW_RIGHT                   32814
#define ID_VIEW_BACK                    32815
#define ID_VIEW_LEFT                    32816
#define ID_VIEW_BOTTOM                  32817
#define ID_VIEW_SHOW                    32819
#define ID_SHOW_FACES                   32820
#define ID_SHOW_CONC_FACES_WIREFRAMES   32822
#define ID_SHOW_LINES                   32823
#define ID_SHOW_POINTS                  32824
#define ID_VIEW_ISOMETRIC               32825
#define ID_VIEW_MODELCHECKER            32826
#define ID_VIEW_MODEL_CHECKER           32827
#define ID_3DVIEW_ENABLE                32831

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        351
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           313
#endif
#endif
