#pragma once

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_PATCH 1
#define VERSION_BUILD 2244

#define STRINGIFY(x) #x
#define STRINGIFY_HELPER(x) STRINGIFY(x)
#define VERSION_STRING STRINGIFY_HELPER(VERSION_MAJOR) "." STRINGIFY_HELPER(VERSION_MINOR) "." STRINGIFY_HELPER(VERSION_PATCH) "." STRINGIFY_HELPER(VERSION_BUILD)


